name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  built-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn --frozen-lockfile
      - run: npm version $GITHUB_REF --git-tag-version=false
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
