name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  built-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Set tag name to outputs 
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Download dependecies
        run: yarn --frozen-lockfile

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          npm version $RELEASE_VERSION --git-tag-version=false
          npm publish
